# Generated by Django 5.2.11 on 2026-02-27 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='protocolo')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='telefone')),
                ('city', models.CharField(blank=True, default='', max_length=180, verbose_name='cidade')),
                ('source', models.CharField(blank=True, default='', max_length=120, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cotacao',
                'verbose_name_plural': 'cotacoes',
                'db_table': 'quote_requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('catalog', 'Catalogo'), ('manual', 'Manual')], default='catalog', max_length=20, verbose_name='modo')),
                ('external_product_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id externo do produto')),
                ('product_name', models.CharField(max_length=255, verbose_name='nome do produto')),
                ('sku', models.CharField(blank=True, default='', max_length=120, verbose_name='sku')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('quality_level', models.CharField(blank=True, default='', max_length=30, verbose_name='nivel de condicao')),
                ('quality_label', models.CharField(blank=True, default='', max_length=255, verbose_name='descricao da condicao')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quoterequest')),
            ],
            options={
                'verbose_name': 'item da cotacao',
                'verbose_name_plural': 'itens da cotacao',
                'db_table': 'quote_request_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quote_requests/%Y/%m/%d/', verbose_name='imagem')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='nome original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.quoterequestitem')),
            ],
            options={
                'verbose_name': 'foto do item da cotacao',
                'verbose_name_plural': 'fotos dos itens da cotacao',
                'db_table': 'quote_request_item_photos',
                'ordering': ['id'],
            },
        ),
    ]
