# Generated by Django 5.2.11 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='admin_conditions',
            field=models.TextField(blank=True, default='', verbose_name='condições / observações'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='admin_price_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor ofertado (R$)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='admin_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='respondida em'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='admin_store_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='crédito de loja (R$)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('respondida', 'Respondida'), ('finalizada', 'Finalizada')], db_index=True, default='recebida', max_length=20, verbose_name='status'),
        ),
    ]
