# Generated by Django 5.2.11 on 2026-02-28 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_per_item_admin_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='protocolo')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='nome do cliente')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail do cliente')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='telefone do cliente')),
                ('customer_city', models.CharField(blank=True, default='', max_length=180, verbose_name='cidade')),
                ('customer_state', models.CharField(blank=True, default='', max_length=50, verbose_name='estado')),
                ('coupon_code', models.CharField(blank=True, default='', max_length=80, verbose_name='cupom')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto total')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor total')),
                ('whatsapp_message', models.TextField(blank=True, default='', verbose_name='mensagem WhatsApp')),
                ('whatsapp_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='url WhatsApp')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('nao_definido', 'Não definido'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], default='nao_definido', max_length=20, verbose_name='meio de pagamento')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='observações internas')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'db_table': 'sales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id do produto')),
                ('product_name', models.CharField(max_length=255, verbose_name='nome do produto')),
                ('platform', models.CharField(blank=True, default='', max_length=120, verbose_name='plataforma')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço unitário')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total do item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale')),
            ],
            options={
                'verbose_name': 'item da venda',
                'verbose_name_plural': 'itens da venda',
                'db_table': 'sale_items',
                'ordering': ['id'],
            },
        ),
    ]
