# Generated by Django 5.2.11 on 2026-03-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='admin_notes',
            field=models.TextField(blank=True, default='', verbose_name='observação geral'),
        ),
    ]
