from django.urls import path

from .views import AsaasCheckoutCreateView, CheckoutCreateSaleView, MercadoPagoCreatePaymentView, MercadoPagoWebhookView, QuoteSubmitView, StorePublicSettingsView, healthcheck
from .admin_views import (
    AdminStatsView,
    AdminCotacoesListView,
    AdminCotacaoDetailView,
    AdminProdutosListView,
    AdminProdutoDetailView,
    AdminClientesListView,
    AdminCategoriasListView,
    AdminCategoriaDetailView,
    AdminPlataformasListView,
    AdminPlataformaDetailView,
    AdminSubplataformasListView,
    AdminSubplataformaDetailView,
    AdminCuponsListView,
    AdminCupomDetailView,
    AdminVendasListView,
    AdminVendaDetailView,
    AdminVendaItemsView,
    AdminVendaItemDetailView,
    AdminVitrinasListView,
    AdminVitrinaDetailView,
    AdminVitrinaItemsView,
    AdminVitrinaItemDetailView,
    AdminProdutosSearchView,
    AdminProdutoImagensView,
    AdminExtratoView,
    AdminStoreSettingsView,
    AdminChangePasswordView,
)

urlpatterns = [
    path("health/", healthcheck, name="api-healthcheck"),
    path("store-settings/", StorePublicSettingsView.as_view(), name="api-store-settings"),
    path("checkout/asaas/", AsaasCheckoutCreateView.as_view(), name="api-checkout-asaas"),
    path("checkout/create-sale/", CheckoutCreateSaleView.as_view(), name="api-checkout-create-sale"),
    path("checkout/mercadopago/create-payment/", MercadoPagoCreatePaymentView.as_view(), name="api-checkout-mp-create"),
    path("checkout/mercadopago/webhook/", MercadoPagoWebhookView.as_view(), name="api-checkout-mp-webhook"),
    path("cotacoes/submit/", QuoteSubmitView.as_view(), name="api-cotacoes-submit"),
    # Admin panel endpoints
    path("admin/stats/", AdminStatsView.as_view(), name="admin-stats"),
    path("admin/cotacoes/", AdminCotacoesListView.as_view(), name="admin-cotacoes-list"),
    path("admin/cotacoes/<int:pk>/", AdminCotacaoDetailView.as_view(), name="admin-cotacao-detail"),
    path("admin/produtos/", AdminProdutosListView.as_view(), name="admin-produtos-list"),
    path("admin/produtos/<int:pk>/", AdminProdutoDetailView.as_view(), name="admin-produto-detail"),
    path("admin/produtos/<int:pk>/imagens/", AdminProdutoImagensView.as_view(), name="admin-produto-imagens"),
    path("admin/clientes/", AdminClientesListView.as_view(), name="admin-clientes-list"),
    path("admin/categorias/", AdminCategoriasListView.as_view(), name="admin-categorias-list"),
    path("admin/categorias/<int:pk>/", AdminCategoriaDetailView.as_view(), name="admin-categoria-detail"),
    path("admin/plataformas/", AdminPlataformasListView.as_view(), name="admin-plataformas-list"),
    path("admin/plataformas/<int:pk>/", AdminPlataformaDetailView.as_view(), name="admin-plataforma-detail"),
    path("admin/subplataformas/", AdminSubplataformasListView.as_view(), name="admin-subplataformas-list"),
    path("admin/subplataformas/<int:pk>/", AdminSubplataformaDetailView.as_view(), name="admin-subplataforma-detail"),
    path("admin/cupons/", AdminCuponsListView.as_view(), name="admin-cupons-list"),
    path("admin/cupons/<int:pk>/", AdminCupomDetailView.as_view(), name="admin-cupom-detail"),
    path("admin/vendas/", AdminVendasListView.as_view(), name="admin-vendas-list"),
    path("admin/vendas/<int:pk>/", AdminVendaDetailView.as_view(), name="admin-venda-detail"),
    path("admin/vendas/<int:pk>/items/", AdminVendaItemsView.as_view(), name="admin-venda-items"),
    path("admin/vendas/<int:pk>/items/<int:item_pk>/", AdminVendaItemDetailView.as_view(), name="admin-venda-item-detail"),
    # Vitrines
    path("admin/vitrines/", AdminVitrinasListView.as_view(), name="admin-vitrines-list"),
    path("admin/vitrines/<int:pk>/", AdminVitrinaDetailView.as_view(), name="admin-vitrine-detail"),
    path("admin/vitrines/<int:pk>/items/", AdminVitrinaItemsView.as_view(), name="admin-vitrine-items"),
    path("admin/vitrines/<int:pk>/items/<int:item_pk>/", AdminVitrinaItemDetailView.as_view(), name="admin-vitrine-item-detail"),
    path("admin/produtos/search/", AdminProdutosSearchView.as_view(), name="admin-produtos-search"),
    path("admin/extrato/", AdminExtratoView.as_view(), name="admin-extrato"),
    path("admin/configuracoes/", AdminStoreSettingsView.as_view(), name="admin-configuracoes"),
    path("admin/change-password/", AdminChangePasswordView.as_view(), name="admin-change-password"),
]
