# Generated by Django 5.2.11 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_city",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="cidade"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_city_ibge",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ibge cidade"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_complement",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="complemento"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_country",
            field=models.CharField(blank=True, default="BRA", max_length=3, verbose_name="país"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_district",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="bairro"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_number",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="número"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_postal_code",
            field=models.CharField(blank=True, default="", max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_reference",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="referência"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_state",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="estado"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_street",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="endereço"),
        ),
    ]

