// Product type lives in lib/types.ts — re-exported here for backward compatibility.
export type { Product } from './types'

export const products: Product[] = [
  {
    id: 1,
    title: 'PlayStation 5 – Console Digital Edition',
    slug: 'playstation-5-digital',
    image: '/images/ps5.jpg',
    images: ['/images/ps5.jpg', '/images/ps5-2.jpg'],
    originalPrice: 3999,
    salePrice: 2799,
    pixPrice: 2659,
    discount: 30,
    platform: 'PS5',
    category: 'console',
    condition: 'Usado',
    inStock: true,
    installments: 10,
    installmentPrice: 279.9,
    sku: 'MGU-001',
    rating: 4.9,
    reviewCount: 128,
    description:
      'PlayStation 5 Digital Edition em perfeito estado de funcionamento. Console sem leitor de disco, ideal para quem compra jogos digitais. Acompanha controle DualSense e cabos originais. Testado e verificado pela equipe Game Shop antes do envio.',
    details: [
      { label: 'Plataforma', value: 'PlayStation 5' },
      { label: 'Modelo', value: 'Digital Edition' },
      { label: 'Armazenamento', value: '825GB SSD' },
      { label: 'Condição', value: 'Usado' },
      { label: 'Acompanha', value: 'Console, 1 Controle DualSense, Cabo HDMI, Cabo USB-C, Base' },
      { label: 'Garantia MGU', value: '6 meses' },
      { label: 'SKU', value: 'MGU-001' },
    ],
  },
  {
    id: 2,
    title: 'Xbox Series X – 1TB SSD',
    slug: 'xbox-series-x',
    image: '/images/xbox-series-x.jpg',
    images: ['/images/xbox-series-x.jpg'],
    originalPrice: 3799,
    salePrice: 2599,
    pixPrice: 2469,
    discount: 32,
    platform: 'Xbox',
    category: 'console',
    condition: 'Seminovo',
    inStock: true,
    installments: 10,
    installmentPrice: 259.9,
    sku: 'MGU-002',
    rating: 4.8,
    reviewCount: 74,
    description:
      'Xbox Series X com 1TB de armazenamento SSD ultrarrápido. Console seminovo em excelente estado, sem riscos ou avarias. Suporta jogos em 4K a 120fps. Acompanha controle original e todos os acessórios.',
    details: [
      { label: 'Plataforma', value: 'Xbox Series X' },
      { label: 'Armazenamento', value: '1TB SSD NVMe' },
      { label: 'Condição', value: 'Seminovo' },
      { label: 'Acompanha', value: 'Console, 1 Controle, Cabo HDMI, Fonte de Alimentação' },
      { label: 'Garantia MGU', value: '9 meses' },
      { label: 'SKU', value: 'MGU-002' },
    ],
  },
  {
    id: 3,
    title: 'Nintendo Switch OLED – Branco',
    slug: 'nintendo-switch-oled',
    image: '/images/nintendo-switch.jpg',
    images: ['/images/nintendo-switch.jpg'],
    originalPrice: 2299,
    salePrice: 1599,
    pixPrice: 1519,
    discount: 30,
    platform: 'Nintendo',
    category: 'console',
    condition: 'Seminovo',
    inStock: true,
    installments: 10,
    installmentPrice: 159.9,
    sku: 'MGU-003',
    rating: 4.9,
    reviewCount: 91,
    description:
      'Nintendo Switch OLED model na cor branca. Tela OLED de 7 polegadas com cores vivas e pretos profundos. Seminovo em ótimo estado, sem arranhões na tela. Perfeito para jogar em qualquer lugar.',
    details: [
      { label: 'Plataforma', value: 'Nintendo Switch OLED' },
      { label: 'Tela', value: '7" OLED' },
      { label: 'Condição', value: 'Seminovo' },
      { label: 'Acompanha', value: 'Console, 2 Joy-Con, Dock, Cabo HDMI, Grip' },
      { label: 'Garantia MGU', value: '6 meses' },
      { label: 'SKU', value: 'MGU-003' },
    ],
  },
  {
    id: 4,
    title: 'PlayStation 4 Slim – 500GB',
    slug: 'playstation-4-slim',
    image: '/images/ps4-slim.jpg',
    images: ['/images/ps4-slim.jpg'],
    originalPrice: 1699,
    salePrice: 1099,
    pixPrice: 1044,
    discount: 35,
    platform: 'PS4',
    category: 'console',
    condition: 'Usado',
    inStock: true,
    installments: 10,
    installmentPrice: 109.9,
    sku: 'MGU-004',
    rating: 4.7,
    reviewCount: 56,
    description:
      'PlayStation 4 Slim com 500GB de armazenamento. Console usado em bom estado, funcionando perfeitamente. Ideal para quem quer entrar no ecossistema PlayStation com um ótimo custo-benefício.',
    details: [
      { label: 'Plataforma', value: 'PlayStation 4 Slim' },
      { label: 'Armazenamento', value: '500GB HDD' },
      { label: 'Condição', value: 'Usado' },
      { label: 'Acompanha', value: 'Console, 1 Controle DualShock 4, Cabo HDMI, Fonte' },
      { label: 'Garantia MGU', value: '3 meses' },
      { label: 'SKU', value: 'MGU-004' },
    ],
  },
  {
    id: 5,
    title: 'Xbox Series S – 512GB',
    slug: 'xbox-series-s',
    image: '/images/xbox-series-s.jpg',
    images: ['/images/xbox-series-s.jpg'],
    originalPrice: 2299,
    salePrice: 1599,
    pixPrice: 1519,
    discount: 30,
    platform: 'Xbox',
    category: 'console',
    condition: 'Usado',
    inStock: true,
    installments: 10,
    installmentPrice: 159.9,
    sku: 'MGU-005',
    rating: 4.6,
    reviewCount: 43,
    description:
      'Xbox Series S compacto e potente. Console all-digital de nova geração com 512GB de armazenamento. Suporta jogos em 1440p com ray tracing. Estado de conservação excelente.',
    details: [
      { label: 'Plataforma', value: 'Xbox Series S' },
      { label: 'Armazenamento', value: '512GB SSD' },
      { label: 'Condição', value: 'Usado' },
      { label: 'Acompanha', value: 'Console, 1 Controle, Cabo HDMI, Fonte de Alimentação' },
      { label: 'Garantia MGU', value: '6 meses' },
      { label: 'SKU', value: 'MGU-005' },
    ],
  },
  {
    id: 6,
    title: 'God of War: Ragnarök – PS5',
    slug: 'god-of-war-ragnarok-ps5',
    image: '/images/god-of-war.jpg',
    images: ['/images/god-of-war.jpg', '/images/god-of-war-2.jpg'],
    originalPrice: 299,
    salePrice: 199,
    pixPrice: 189,
    discount: 33,
    platform: 'PS5',
    category: 'jogo',
    condition: 'Usado',
    inStock: true,
    installments: 10,
    installmentPrice: 19.9,
    sku: 'MGU-006',
    rating: 5.0,
    reviewCount: 215,
    description:
      'God of War: Ragnarök para PlayStation 5. Jogo em mídia física, disco em perfeito estado sem arranhões. Uma das maiores aventuras de Kratos e Atreus. Compatível com PS5 e aproveitando todos os recursos do DualSense.',
    details: [
      { label: 'Plataforma', value: 'PlayStation 5' },
      { label: 'Gênero', value: 'Ação / Aventura' },
      { label: 'Desenvolvedora', value: 'Santa Monica Studio' },
      { label: 'Condição', value: 'Usado' },
      { label: 'Mídia', value: 'Física (Blu-ray)' },
      { label: 'Classificação', value: '16 anos' },
      { label: 'Garantia MGU', value: '3 meses' },
      { label: 'SKU', value: 'MGU-006' },
    ],
  },
  {
    id: 7,
    title: "Marvel's Spider-Man 2 – PS5",
    slug: 'spider-man-2-ps5',
    image: '/images/spider-man.jpg',
    images: ['/images/spider-man.jpg'],
    originalPrice: 349,
    salePrice: 249,
    pixPrice: 236,
    discount: 29,
    platform: 'PS5',
    category: 'jogo',
    condition: 'Seminovo',
    inStock: true,
    installments: 10,
    installmentPrice: 24.9,
    sku: 'MGU-007',
    rating: 4.9,
    reviewCount: 187,
    description:
      "Marvel's Spider-Man 2 para PlayStation 5. Jogo seminovo em estado impecável. Experimente Nova York como nunca antes com dois Homens-Aranha jogáveis. Aproveite os recursos hápticos do DualSense.",
    details: [
      { label: 'Plataforma', value: 'PlayStation 5' },
      { label: 'Gênero', value: 'Ação / Mundo Aberto' },
      { label: 'Desenvolvedora', value: 'Insomniac Games' },
      { label: 'Condição', value: 'Seminovo' },
      { label: 'Mídia', value: 'Física (Blu-ray)' },
      { label: 'Classificação', value: '14 anos' },
      { label: 'Garantia MGU', value: '3 meses' },
      { label: 'SKU', value: 'MGU-007' },
    ],
  },
  {
    id: 8,
    title: 'The Legend of Zelda: Tears of the Kingdom',
    slug: 'zelda-tears-of-the-kingdom',
    image: '/images/zelda.jpg',
    images: ['/images/zelda.jpg'],
    originalPrice: 349,
    salePrice: 259,
    pixPrice: 246,
    discount: 26,
    platform: 'Nintendo',
    category: 'jogo',
    condition: 'Usado',
    inStock: true,
    installments: 10,
    installmentPrice: 25.9,
    sku: 'MGU-008',
    rating: 5.0,
    reviewCount: 302,
    description:
      'The Legend of Zelda: Tears of the Kingdom para Nintendo Switch. Jogo usado em ótimo estado. Explore Hyrule de cima a baixo nesta épica aventura. Um dos melhores jogos de todos os tempos.',
    details: [
      { label: 'Plataforma', value: 'Nintendo Switch' },
      { label: 'Gênero', value: 'Aventura / RPG' },
      { label: 'Desenvolvedora', value: 'Nintendo EPD' },
      { label: 'Condição', value: 'Usado' },
      { label: 'Mídia', value: 'Física (Cartucho)' },
      { label: 'Classificação', value: '10 anos' },
      { label: 'Garantia MGU', value: '3 meses' },
      { label: 'SKU', value: 'MGU-008' },
    ],
  },
  {
    id: 9,
    title: 'FIFA 24 – PS4/PS5',
    slug: 'fifa-24-ps5',
    image: '/images/fifa.jpg',
    images: ['/images/fifa.jpg'],
    originalPrice: 299,
    salePrice: 179,
    pixPrice: 170,
    discount: 40,
    platform: 'PS5',
    category: 'jogo',
    condition: 'Usado',
    inStock: true,
    installments: 10,
    installmentPrice: 17.9,
    sku: 'MGU-009',
    rating: 4.5,
    reviewCount: 98,
    description:
      'FIFA 24 edição dupla PS4/PS5. Disco em bom estado de conservação. Aproveite a temporada mais realista do futebol virtual com HyperMotion V e mais de 700 equipes licenciadas.',
    details: [
      { label: 'Plataforma', value: 'PS4 / PS5' },
      { label: 'Gênero', value: 'Esporte / Futebol' },
      { label: 'Desenvolvedora', value: 'EA Sports' },
      { label: 'Condição', value: 'Usado' },
      { label: 'Mídia', value: 'Física (Blu-ray)' },
      { label: 'Classificação', value: 'Livre' },
      { label: 'Garantia MGU', value: '3 meses' },
      { label: 'SKU', value: 'MGU-009' },
    ],
  },
  {
    id: 10,
    title: 'Mortal Kombat 11 Ultimate – PS4',
    slug: 'mortal-kombat-11-ps4',
    image: '/images/mk11.jpg',
    images: ['/images/mk11.jpg'],
    originalPrice: 249,
    salePrice: 129,
    pixPrice: 122,
    discount: 48,
    platform: 'PS4',
    category: 'jogo',
    condition: 'Usado',
    inStock: true,
    installments: 10,
    installmentPrice: 12.9,
    sku: 'MGU-010',
    rating: 4.7,
    reviewCount: 63,
    description:
      'Mortal Kombat 11 Ultimate para PlayStation 4. Inclui o jogo base e todos os DLCs. Disco em perfeito estado. A edição definitiva do melhor jogo de luta da geração.',
    details: [
      { label: 'Plataforma', value: 'PlayStation 4' },
      { label: 'Gênero', value: 'Luta' },
      { label: 'Desenvolvedora', value: 'NetherRealm Studios' },
      { label: 'Condição', value: 'Usado' },
      { label: 'Mídia', value: 'Física (Blu-ray)' },
      { label: 'Classificação', value: '18 anos' },
      { label: 'Garantia MGU', value: '3 meses' },
      { label: 'SKU', value: 'MGU-010' },
    ],
  },
]

export const categories = [
  { label: 'PLAYSTATION', href: '/busca?q=playstation', icon: '🎮' },
  { label: 'XBOX', href: '/busca?q=xbox', icon: '🕹️' },
  { label: 'NINTENDO', href: '/busca?q=nintendo', icon: '🎯' },
  { label: 'RARIDADES', href: '/busca', icon: '⭐' },
  { label: 'PCs & NOTEBOOKS', href: '/busca?q=pc', icon: '💻' },
  { label: 'OUTROS', href: '/busca', icon: '📦' },
]

export const trustBadges = [
  {
    id: 1,
    icon: 'credit-card',
    title: '10x sem juros',
    subtitle: 'No cartão de crédito',
  },
  {
    id: 2,
    icon: 'shield',
    title: 'Garantia de até 9 meses',
    subtitle: 'Em todos os produtos',
  },
  {
    id: 3,
    icon: 'star',
    title: 'Novidades todos os dias',
    subtitle: 'Estoque sempre renovado',
  },
  {
    id: 4,
    icon: 'truck',
    title: 'Envio para todo o Brasil',
    subtitle: 'Frete rápido e seguro',
  },
  {
    id: 5,
    icon: 'lock',
    title: 'SSL 100% seguro',
    subtitle: 'Sua compra protegida',
  },
]

export const promoCards = [
  {
    id: 1,
    title: 'Venda seus produtos para a Game Shop',
    description: 'Receba dinheiro rápido pelos seus games e consoles usados.',
    cta: 'Saiba mais',
    href: '/cotacoes',
    image: '/images/promo-sell.jpg',
    gradient: 'from-yellow-900 to-yellow-600',
    badge: 'COMPRA GARANTIDA',
  },
  {
    id: 2,
    title: 'Consoles no Game Shop',
    description: 'Descontos de até 60% nos melhores consoles.',
    cta: 'Saiba mais',
    href: '/busca?categoria=consoles',
    image: '/images/promo-consoles.jpg',
    gradient: 'from-purple-900 to-purple-600',
    badge: 'ATÉ 60% OFF',
  },
  {
    id: 3,
    title: 'Jogos no Game Shop',
    description: 'Descontos de até 80% nos seus games favoritos.',
    cta: 'Saiba mais',
    href: '/busca?categoria=jogos',
    image: '/images/promo-games.jpg',
    gradient: 'from-red-900 to-red-600',
    badge: 'ATÉ 80% OFF',
  },
]
