# Generated by Django 5.2.11 on 2026-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='id externo')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='sku')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=600, verbose_name='url da capa')),
                ('local_image_path', models.CharField(blank=True, default='', max_length=600, verbose_name='caminho local da imagem')),
                ('image_exists', models.BooleanField(default=False, verbose_name='imagem local existe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'produto de cotacao',
                'verbose_name_plural': 'produtos de cotacao',
                'db_table': 'quote_products',
                'ordering': ['external_id'],
            },
        ),
    ]
