# Generated by Django 5.2.11 on 2026-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_quoteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteproduct',
            name='sku',
            field=models.CharField(db_index=True, max_length=100, verbose_name='sku'),
        ),
    ]
