# Generated by Django 5.2.11 on 2026-02-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_id_alter_platform_id'),
        ('products', '0007_showcase'),
    ]

    operations = [
    ]
