# Generated by Django 5.2.11 on 2026-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_showcase_id_alter_showcaseitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentual'), ('FIXED', 'Valor fixo')], default='PERCENT', max_length=10, verbose_name='tipo de desconto')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do desconto')),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor mínimo do pedido')),
                ('max_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='desconto máximo')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de uso')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='total de usos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'db_table': 'coupons',
                'ordering': ['-id'],
            },
        ),
    ]
