# Generated by Django 5.2.11 on 2026-02-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limite por usuario'),
        ),
    ]
