# Generated by Django 5.2.11 on 2026-03-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subplatform',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='subplataforma'),
        ),
        migrations.CreateModel(
            name='Subplatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subplatforms', to='products.platform', verbose_name='plataforma')),
            ],
            options={
                'verbose_name': 'subplataforma',
                'verbose_name_plural': 'subplataformas',
                'db_table': 'subplatforms',
                'ordering': ['platform__name', 'name'],
                'unique_together': {('platform', 'name')},
            },
        ),
    ]
