# Generated by Django 5.2.11 on 2026-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_subplatform_subplatform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcase',
            options={'ordering': ['order', 'id'], 'verbose_name': 'vitrine', 'verbose_name_plural': 'vitrines'},
        ),
        migrations.AddField(
            model_name='showcase',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordem'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='subtítulo exibido'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='título exibido'),
        ),
    ]
