# Generated by Django 5.2.11 on 2026-03-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_showcase_options_showcase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_zero_stock_products',
            field=models.BooleanField(default=False, help_text='Se ativo, produtos com estoque zero são exibidos na vitrine/busca.', verbose_name='mostrar produtos sem estoque'),
        ),
    ]
