# Generated by Django 5.2.11 on 2026-03-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_show_zero_stock_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_zero_price_products',
            field=models.BooleanField(default=False, help_text='Se ativo, produtos com preço zero são exibidos na vitrine/busca.', verbose_name='mostrar produtos com valor zerado'),
        ),
    ]
